import { EmailType } from "./types/email";

export const emails: EmailType[] =  [
    {
        id: 1,
        subject: "Meeting Agenda",
        sender: "john.doe@example.com",
        receiver: "team@example.com",
        date: "2024-02-28",
        body: "Hi team,\n\nLet's discuss the agenda for our upcoming meeting. Please find the attached document.\n\nBest regards,\nJohn",
    },
    {
        id: 2,
        subject: "Project Update",
        sender: "project.manager@example.com",
        receiver: "developer@example.com",
        date: "2024-02-28",
        body: "Hi team,\n\nI wanted to provide an update on the project's progress. We've successfully completed the latest milestone.\n\nBest regards,\nProject Manager",
    },
    {
        id: 3,
        subject: "Invitation to Webinar",
        sender: "webinar.host@example.com",
        receiver: "attendee@example.com",
        date: "2024-03-05",
        body: "Dear [Attendee],\n\nYou're invited to our upcoming webinar on [Topic]. Please register using the provided link.\n\nBest regards,\nWebinar Host",
    },
    {
        id: 4,
        subject: "Job Application Acknowledgment",
        sender: "hr@example.com",
        receiver: "applicant@example.com",
        date: "2024-03-10",
        body: "Dear [Applicant],\n\nWe have received your job application. Our team will review it, and we will be in touch soon.\n\nBest regards,\nHR Team",
    },
    {
        id: 5,
        subject: "Event Reminder",
        sender: "event.organizer@example.com",
        receiver: "attendee@example.com",
        date: "2024-03-15",
        body: "Hi [Attendee],\n\nThis is a reminder for the upcoming event on [Date]. We look forward to seeing you there!\n\nBest regards,\nEvent Organizer",
    },
    {
        id: 6,
        subject: "Product Launch Announcement",
        sender: "company.marketing@example.com",
        receiver: "customers@example.com",
        date: "2024-03-20",
        body: "Dear Customer,\n\nWe are excited to announce the launch of our new product. Visit our website for more details!\n\nBest regards,\nMarketing Team",
    },
    {
        id: 7,
        subject: "Feedback Request",
        sender: "support@example.com",
        receiver: "customer@example.com",
        date: "2024-03-25",
        body: "Dear [Customer],\n\nWe value your feedback! Please take a moment to share your thoughts on our services.\n\nBest regards,\nCustomer Support",
    },
    {
        id: 8,
        subject: "Birthday Greetings",
        sender: "ceo@example.com",
        receiver: "employee@example.com",
        date: "2024-04-02",
        body: "Dear [Employee],\n\nWishing you a fantastic birthday! May this year bring you joy and success.\n\nBest regards,\nCEO",
    },
    {
        id: 9,
        subject: "Password Reset Confirmation",
        sender: "security@example.com",
        receiver: "user@example.com",
        date: "2024-04-08",
        body: "Hi [User],\n\nYour password reset request has been confirmed. If you didn't make this request, please contact our support.\n\nBest regards,\nSecurity Team",
    },
    {
        id: 10,
        subject: "Holiday Greetings",
        sender: "team.leader@example.com",
        receiver: "team@example.com",
        date: "2024-04-15",
        body: "Hi team,\n\nWishing you a joyful holiday season. Thank you for your hard work and dedication.\n\nBest regards,\nTeam Leader",
    },
];
